plugins:
  # audio:
  #   data: <data directory?>
  cli:
  dispatch:
    wit_token: <WIT token>

device-manager:
  path: <path to device manager executable>
  addr: <socket address to listen for plugin connections on>
  log-level: debug
  index-cache: <path to seshat index cache file (json)>
  index-root: <optional array of system root folder paths>

# ai-manager:
#   path: <path to ai manager executable>
#   addr: <socket address to listen for connections on>
#   log-level: warn

loader_config:
  script_path: <Path to the python loader script>
  plugin-dir: <Path to the plugins dir. NOTE What is this doing?>
  port: <port to connect on>  # NOTE: These must match the socket address the device-manager is listening on
  log-dir: ./log
  retry-delay: <number of seconds between retrying initial connection if it fails>
  max-retries: <maximum number of retries before connection is considered broken>
