[package]
name = "seshat"
version = "0.1.0"
authors = ["Grayson Hooper <ghooper96@gmail.com>"]

[dependencies]
walkdir = "2.1.4"

tags = { path="../tags" }
array_tool = "1.0.3"
serde_json = "1.0.27"
serde_derive = "1.0.78"
serde = "1.0.78"
evmap = "4.0.0"
