[package]
name = "server"
version = "0.1.0"
authors = ["Grayson Hooper <ghooper96@gmail.com>"]

[dependencies]
tokio = "0.1.6"
tokio-serde-json = { git = "https://github.com/carllerche/tokio-serde-json" }
tokio-tcp = "0.1.0"
tokio-io = "0.1.6"
